/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'justin' at '11/03/17 7:57 AM' with Gradle 2.14.1
 *
 * @author justin, @date 11/03/17 7:57 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
